<a href="https://colab.research.google.com/github/rupanshi1627-create/NumPyandPANDAS/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
#SERIES-- how to create a series 1-- using list
import pandas as pd
import numpy as np
country=["India",'Pakistan','america'] #ye ek list hai isse s
pd.Series(country)

0       India
1    Pakistan
2     america
dtype: object

In [68]:
#read csv

movies=pd.read_csv('/content/archive (3).zip')
# To sort a DataFrame, you must specify the column name using the 'by' parameter
movies.sort_values(by='budget',ascending=False).head(1)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
17,17,380000000,Adventure Action Fantasy,http://disney.go.com/pirates/index-on-stranger...,1865,sea captain mutiny sword prime minister,en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,135.413856,...,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948,Johnny Depp Pen\u00e9lope Cruz Ian McShane Kev...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Rob Marshall