<a href="https://colab.research.google.com/github/rupanshi1627-create/NumPyandPANDAS/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#SERIES-- how to create a series 1-- using list
import pandas as pd
import numpy as np
country=["India",'Pakistan','america'] #ye ek list hai isse s
pd.Series(country)

0       India
1    Pakistan
2     america
dtype: object

In [ ]:
#read csv and
#sort_values
movies=pd.read_csv('/content/archive (3).zip')
# To sort a DataFrame, you must specify the column name using the 'by' parameter
movies.sort_values(by='budget',ascending=False).head(1)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
17,17,380000000,Adventure Action Fantasy,http://disney.go.com/pirates/index-on-stranger...,1865,sea captain mutiny sword prime minister,en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,135.413856,...,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948,Johnny Depp Pen\u00e9lope Cruz Ian McShane Kev...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Rob Marshall

In [ ]:
movies.sort_values(by='genres')

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
1528,1528,31500000,Action,NaN,302156,cia memory convict implant,en,Criminal,Bill Pope is a CIA agent on a mission in Londo...,27.891012,...,113.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Criminal,5.7,557,Kevin Costner Gary Oldman Tommy Lee Jones Ryan...,"[{'name': 'Chris Bender', 'gender': 2, 'depart...",Ariel Vromen
2777,2777,3000000,Action,NaN,24227,police shoulder holster police shootout shooto...,en,Excessive Force,Chicago policeman Terry McCain is determined t...,1.279106,...,87.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You have the right to remain silent... permane...,Excessive Force,4.5,10,Thomas Ian Griffith Lance Henriksen James Earl...,"[{'name': 'Thomas Ian Griffith', 'gender': 2, ...",Jon Hess
1701,1701,29000000,Action,NaN,1428,corruption cia,en,Once Upon a Time in Mexico,"Hitman ""El Mariachi"" becomes involved in inter...",27.555646,...,102.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The Time Has Come.,Once Upon a Time in Mexico,6.2,594,Antonio Banderas Salma Hayek Johnny Depp Eva M...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
1741,1741,24000000,Action,NaN,13495,NaN,es,Alatriste,"In 17th century Spain Diego Alatriste, a brave...",6.009644,...,145.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,NaN,Alatriste,5.6,61,Viggo Mortensen Elena Anaya Unax Ugalde Eduard...,"[{'name': 'Jos\\u00e9 Salcedo', 'gender': 2, '...",Agust\u00edn D\u00edaz Yanes
44,44,190000000,Action,http://www.furious7.com/,168259,car race speed revenge suspense car,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,102.322217,...,137.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Vengeance Hits Home,Furious 7,7.3,4176,Vin Diesel Paul Walker Dwayne Johnson Michelle...,"[{'name': 'James Wan', 'gender': 2, 'departmen...",James Wan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4674,4674,0,NaN,NaN,194588,NaN,en,Short Cut to Nirvana: Kumbh Mela,Every 12 years over 70 million pilgrims gather...,0.004998,...,85.0,[],Released,NaN,Short Cut to Nirvana: Kumbh Mela,0.0,0,NaN,[],NaN
4681,4681,0,NaN,http://www.realityshowthefilm.com/,176074,wife husband relationship reality reality tv r...,en,Reality Show,The Warwick family are unknowingly being filme...,0.472123,...,92.0,[],Released,NaN,Reality Show,5.5,2,Adam Rifkin Kelley Menighan Hensley Kendra Sue...,"[{'name': 'Adam Rifkin', 'gender': 2, 'departm...",Adam Rifkin
4714,4714,0,NaN,NaN,282128,NaN,en,An American in Hollywood,A talented young filmmaker from New York sets ...,0.015697,...,89.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,An American in Hollywood,0.0,0,J.D. Williams Hassan Johnson Anil Raman Richar...,"[{'name': 'Sai Varadan', 'gender': 0, 'departm...",Sai Varadan
4716,4716,0,NaN,NaN,38786,NaN,en,The Blood of My Brother: A Story of Death in Iraq,THE BLOOD OF MY BROTHER goes behind the scenes...,0.005256,...,90.0,[],Released,NaN,The Blood of My Brother: A Story of Death in Iraq,0.0,0,NaN,[],NaN
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia

In [ ]:
movies.describe()

,index,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4803.000000,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2401.000000,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,1386.651002,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,1200.500000,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,2401.000000,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,3601.500000,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,4802.000000,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [ ]:
 only=movies[['index','budget']]
 print(movies)